final class ExactBuffInfo {
  const ExactBuffInfo({
    required this.title,
    required this.effects,
    this.duration = '',
    this.cooldown = '',
    this.party = false,
  });

  final String title;
  final List<String> effects;
  final String duration;
  final String cooldown;
  final bool party;
}

final Map<String, ExactBuffInfo> exactBuffInfoByName = <String, ExactBuffInfo>{
  'adaptation draught': ExactBuffInfo(
    title: 'Adaptation Draught',
    effects: <String>[
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'agile seal elixir': ExactBuffInfo(
    title: 'Agile Seal Elixir',
    effects: <String>['Underwater Breathing +15 sec'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'antidote elixir': ExactBuffInfo(
    title: 'Antidote Elixir',
    effects: <String>['Cures Intoxication'],
    duration: 'Instant',
    cooldown: '30 sec',
  ),
  'armor draught': ExactBuffInfo(
    title: 'Armor Draught',
    effects: <String>[
      'All Damage Reduction +15',
      'All Evasion +10',
      'Monster Damage Reduction Rate +12%',
      'Max HP +300',
      'Ignore All Resistance +5%',
      'All AP -15',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'beast\'s draught': ExactBuffInfo(
    title: 'Beast\'s Draught',
    effects: <String>[
      'Extra AP Against Monsters +15',
      'Combat EXP +20%',
      'Skill EXP +10%',
      'Recover 3 HP on Hits',
      'Monster Damage Reduction Rate +10%',
      'Critical Hit +3',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'berserk draught': ExactBuffInfo(
    title: 'Berserk Draught',
    effects: <String>['All Special Attack Extra Damage +16%'],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'blessing of mystic beasts - accuracy': ExactBuffInfo(
    title: 'Blessing of Mystic Beasts - Accuracy',
    effects: <String>['All Accuracy +20'],
    duration: '60 min',
    cooldown: '10 sec',
  ),
  'blessing of mystic beasts - all ap': ExactBuffInfo(
    title: 'Blessing of Mystic Beasts - All AP',
    effects: <String>['All AP +15'],
    duration: '60 min',
    cooldown: '10 sec',
  ),
  'blessing of mystic beasts - damage reduction': ExactBuffInfo(
    title: 'Blessing of Mystic Beasts - Damage Reduction',
    effects: <String>['All Damage Reduction +15'],
    duration: '60 min',
    cooldown: '10 sec',
  ),
  'blessing of mystic beasts - evasion': ExactBuffInfo(
    title: 'Blessing of Mystic Beasts - Evasion',
    effects: <String>['All Evasion +20'],
    duration: '60 min',
    cooldown: '10 sec',
  ),
  'blessing of mystic beasts - max hp': ExactBuffInfo(
    title: 'Blessing of Mystic Beasts - Max HP',
    effects: <String>['Max HP +100'],
    duration: '60 min',
    cooldown: '10 sec',
  ),
  'blue tidal draught': ExactBuffInfo(
    title: 'Blue Tidal Draught',
    effects: <String>[
      'Fishing EXP +20%',
      'Fishing Speed +2',
      'Fishing Mastery +50',
    ],
    duration: '360 min',
    cooldown: '10 sec',
  ),
  'brutal death elixir': ExactBuffInfo(
    title: 'Brutal Death Elixir',
    effects: <String>['Deal 15 Fixed Damage on Critical Hits'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'celerity draught': ExactBuffInfo(
    title: 'Celerity Draught',
    effects: <String>[
      'Mount EXP +15%',
      'Training EXP +20%',
      'Sailing EXP +20%',
      'Movement Speed +3',
    ],
    duration: '180 min',
    cooldown: '10 sec',
  ),
  'corruption draught': ExactBuffInfo(
    title: 'Corruption Draught',
    effects: <String>[
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'deep blue tidal draught': ExactBuffInfo(
    title: 'Deep Blue Tidal Draught',
    effects: <String>[
      'Fishing EXP +30%',
      'Fishing Speed +3',
      'Fishing Mastery +100',
    ],
    duration: '600 min',
    cooldown: '10 sec',
  ),
  'defense elixir': ExactBuffInfo(
    title: 'Defense Elixir',
    effects: <String>['All Damage Reduction +5'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'exp elixir': ExactBuffInfo(
    title: 'EXP Elixir',
    effects: <String>['Combat EXP +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of advanced concentration': ExactBuffInfo(
    title: 'Elixir of Advanced Concentration',
    effects: <String>['All Accuracy +12'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of agile spells': ExactBuffInfo(
    title: 'Elixir of Agile Spells',
    effects: <String>['Casting Speed +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of amity': ExactBuffInfo(
    title: 'Elixir of Amity',
    effects: <String>['Amity +20%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of armor': ExactBuffInfo(
    title: 'Elixir of Armor',
    effects: <String>[
      'All Damage Reduction +8',
      'Monster Damage Reduction Rate +7.5%',
      'All AP -3',
    ],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of assassination': ExactBuffInfo(
    title: 'Elixir of Assassination',
    effects: <String>['Back Attack Extra Damage +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of brawn': ExactBuffInfo(
    title: 'Elixir of Brawn',
    effects: <String>['Strength EXP +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of brutal carnage': ExactBuffInfo(
    title: 'Elixir of Brutal Carnage',
    effects: <String>['Down Attack Extra Damage +15%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of brutal perforation': ExactBuffInfo(
    title: 'Elixir of Brutal Perforation',
    effects: <String>['Deal 15 Fixed Damage on Back Attack Hits'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of burn removal': ExactBuffInfo(
    title: 'Elixir of Burn Removal',
    effects: <String>['Cures Burns'],
    duration: 'Instant',
    cooldown: '30 sec',
  ),
  'elixir of carnage': ExactBuffInfo(
    title: 'Elixir of Carnage',
    effects: <String>['Down Attack Extra Damage +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of clear mentality': ExactBuffInfo(
    title: 'Elixir of Clear Mentality',
    effects: <String>['Max MP +150'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of concentration': ExactBuffInfo(
    title: 'Elixir of Concentration',
    effects: <String>['All Accuracy +8'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of corrupted armor': ExactBuffInfo(
    title: 'Elixir of Corrupted Armor',
    effects: <String>[
      'All Damage Reduction +12',
      'Monster Damage Reduction Rate +10%',
      'All AP -5',
    ],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of death': ExactBuffInfo(
    title: 'Elixir of Death',
    effects: <String>['Deal 7 Fixed Damage on Critical Hits'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of demihuman hunt': ExactBuffInfo(
    title: 'Elixir of Demihuman Hunt',
    effects: <String>['Extra AP Against Demihumans +10'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of destruction': ExactBuffInfo(
    title: 'Elixir of Destruction',
    effects: <String>['All Special Attack Extra Damage +1%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of detection': ExactBuffInfo(
    title: 'Elixir of Detection',
    effects: <String>['Critical Hit Extra Damage +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of draining': ExactBuffInfo(
    title: 'Elixir of Draining',
    effects: <String>['Recover 9 HP on Critical Hits'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of edania': ExactBuffInfo(
    title: 'Elixir of Edania',
    effects: <String>['Extra AP Against Edanian Monsters +12'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of endless frenzy': ExactBuffInfo(
    title: 'Elixir of Endless Frenzy',
    effects: <String>['All DP -8', 'All AP +13'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of endless fury': ExactBuffInfo(
    title: 'Elixir of Endless Fury',
    effects: <String>['All AP +8'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of endless persistence': ExactBuffInfo(
    title: 'Elixir of Endless Persistence',
    effects: <String>['Breath EXP +20%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of endurance': ExactBuffInfo(
    title: 'Elixir of Endurance',
    effects: <String>['Max Stamina +100'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of energy': ExactBuffInfo(
    title: 'Elixir of Energy',
    effects: <String>['MP Recovery +10'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of expert training': ExactBuffInfo(
    title: 'Elixir of Expert Training',
    effects: <String>['Mount EXP +10%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of fierce demihuman hunt': ExactBuffInfo(
    title: 'Elixir of Fierce Demihuman Hunt',
    effects: <String>['Extra AP Against Demihumans +15'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of flowing time': ExactBuffInfo(
    title: 'Elixir of Flowing Time',
    effects: <String>['Life EXP +15%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of flowing wind': ExactBuffInfo(
    title: 'Elixir of Flowing Wind',
    effects: <String>['Attack Speed +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of frenzy': ExactBuffInfo(
    title: 'Elixir of Frenzy',
    effects: <String>['All DP -5', 'All AP +10'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of fury': ExactBuffInfo(
    title: 'Elixir of Fury',
    effects: <String>['All AP +5'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of hemostasis': ExactBuffInfo(
    title: 'Elixir of Hemostasis',
    effects: <String>['Cures Bleeding'],
    duration: 'Instant',
    cooldown: '30 sec',
  ),
  'elixir of human hunt': ExactBuffInfo(
    title: 'Elixir of Human Hunt',
    effects: <String>[
      'Extra AP Against Adventurers +6',
      'Extra AP Against Humans +6',
    ],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of improved mastery': ExactBuffInfo(
    title: 'Elixir of Improved Mastery',
    effects: <String>[
      'Life Skill Mastery +15',
      'Constant reduction of MP/WP/SP',
    ],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of indignation': ExactBuffInfo(
    title: 'Elixir of Indignation',
    effects: <String>[
      'Extra AP Against Adventurers +25',
      'Extra AP Against Humans +25',
      'All Special Attack Extra Damage +12%',
      'Movement Speed +3',
      'Critical Hit +3',
      'Max Stamina +200',
      'Max HP -150',
      'All Damage Reduction -20',
      'All Evasion -20',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'elixir of infinite skill': ExactBuffInfo(
    title: 'Elixir of Infinite Skill',
    effects: <String>['Skill EXP +15%', 'Movement Speed -30%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of intrepid swiftness': ExactBuffInfo(
    title: 'Elixir of Intrepid Swiftness',
    effects: <String>['Movement Speed +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of labor': ExactBuffInfo(
    title: 'Elixir of Labor',
    effects: <String>[
      'Gathering Item Drop Rate +3%',
      'Constant reduction of MP/WP/SP',
    ],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of lethal assassin': ExactBuffInfo(
    title: 'Elixir of Lethal Assassin',
    effects: <String>['Back Attack Extra Damage +15%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of lethal destruction': ExactBuffInfo(
    title: 'Elixir of Lethal Destruction',
    effects: <String>['All Special Attack Extra Damage +2%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of life': ExactBuffInfo(
    title: 'Elixir of Life',
    effects: <String>['Max HP +100'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of mastery': ExactBuffInfo(
    title: 'Elixir of Mastery',
    effects: <String>[
      'Life Skill Mastery +10',
      'Constant reduction of MP/WP/SP',
    ],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of mentality': ExactBuffInfo(
    title: 'Elixir of Mentality',
    effects: <String>['Max MP +100'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of overwhelming endurance': ExactBuffInfo(
    title: 'Elixir of Overwhelming Endurance',
    effects: <String>['Max Stamina +150'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of perfect human hunt': ExactBuffInfo(
    title: 'Elixir of Perfect Human Hunt',
    effects: <String>[
      'Extra AP Against Adventurers +11',
      'Extra AP Against Humans +11',
    ],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of perforation': ExactBuffInfo(
    title: 'Elixir of Perforation',
    effects: <String>['Deal 7 Fixed Damage on Back Attack Hits'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of persistence': ExactBuffInfo(
    title: 'Elixir of Persistence',
    effects: <String>['Breath EXP +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of raw brawn': ExactBuffInfo(
    title: 'Elixir of Raw Brawn',
    effects: <String>['Strength EXP +20%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of remarkable will': ExactBuffInfo(
    title: 'Elixir of Remarkable Will',
    effects: <String>['Monster Damage Reduction Rate +10%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of regeneration': ExactBuffInfo(
    title: 'Elixir of Regeneration',
    effects: <String>['Cures one sailor', 'Recovers sailor condition to 100%'],
  ),
  'elixir of resistance': ExactBuffInfo(
    title: 'Elixir of Resistance',
    effects: <String>['All Resistance +5%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of rough labor': ExactBuffInfo(
    title: 'Elixir of Rough Labor',
    effects: <String>[
      'Gathering Item Drop Rate +5%',
      'Constant reduction of MP/WP/SP',
    ],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of seal': ExactBuffInfo(
    title: 'Elixir of Seal',
    effects: <String>['Underwater Breathing +10 sec'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of sharp detection': ExactBuffInfo(
    title: 'Elixir of Sharp Detection',
    effects: <String>['Critical Hit Extra Damage +15%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of sharp resistance': ExactBuffInfo(
    title: 'Elixir of Sharp Resistance',
    effects: <String>['All Resistance +8%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of sharp thorn': ExactBuffInfo(
    title: 'Elixir of Sharp Thorn',
    effects: <String>['Target\'s HP -15 when struck'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of shock': ExactBuffInfo(
    title: 'Elixir of Shock',
    effects: <String>['Critical Hit +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of skill': ExactBuffInfo(
    title: 'Elixir of Skill',
    effects: <String>['Skill EXP +10%', 'Movement Speed -20%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of sky': ExactBuffInfo(
    title: 'Elixir of Sky',
    effects: <String>['Air Attack Extra Damage +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of spells': ExactBuffInfo(
    title: 'Elixir of Spells',
    effects: <String>['Casting Speed +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of steel defense': ExactBuffInfo(
    title: 'Elixir of Steel Defense',
    effects: <String>['All Damage Reduction +10'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of strong draining': ExactBuffInfo(
    title: 'Elixir of Strong Draining',
    effects: <String>['Recover 15 HP on Critical Hits'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of strong life': ExactBuffInfo(
    title: 'Elixir of Strong Life',
    effects: <String>['Max HP +150'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of strong shock': ExactBuffInfo(
    title: 'Elixir of Strong Shock',
    effects: <String>['Critical Hit +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of swiftness': ExactBuffInfo(
    title: 'Elixir of Swiftness',
    effects: <String>['Movement Speed +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of thorn': ExactBuffInfo(
    title: 'Elixir of Thorn',
    effects: <String>['Target\'s HP -10 when struck'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of time': ExactBuffInfo(
    title: 'Elixir of Time',
    effects: <String>['Life EXP +10%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of training': ExactBuffInfo(
    title: 'Elixir of Training',
    effects: <String>['Mount EXP +8%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of will': ExactBuffInfo(
    title: 'Elixir of Will',
    effects: <String>['Monster Damage Reduction Rate +7.5%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of wind': ExactBuffInfo(
    title: 'Elixir of Wind',
    effects: <String>['Attack Speed +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'elixir of wings': ExactBuffInfo(
    title: 'Elixir of Wings',
    effects: <String>['Jump Height +20'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'fiery celerity draught': ExactBuffInfo(
    title: 'Fiery Celerity Draught',
    effects: <String>['Mount EXP +30%', 'Training EXP +30%'],
    duration: '600 min',
    cooldown: '10 sec',
  ),
  'fisher\'s elixir': ExactBuffInfo(
    title: 'Fisher\'s Elixir',
    effects: <String>['Fishing Speed +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'frenzy draught': ExactBuffInfo(
    title: 'Frenzy Draught',
    effects: <String>[
      'Extra AP Against Monsters +30',
      'All Accuracy +12',
      'Max Stamina +200',
      'Recover 9 HP on Hits',
      'All Damage Reduction -15',
      'Critical Hit Extra Damage +10%',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'frenzy draught of corruption': ExactBuffInfo(
    title: 'Frenzy Draught of Corruption',
    effects: <String>[
      'Extra AP Against Monsters +35',
      'All Accuracy +12',
      'Max Stamina +200',
      'Recover 9 HP on Hits',
      'All Damage Reduction -15',
      'Critical Hit Extra Damage +10%',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'fury draught': ExactBuffInfo(
    title: 'Fury Draught',
    effects: <String>[
      'All AP +13',
      'All Accuracy +13',
      'All Special Attack Extra Damage +2%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'giant\'s draught': ExactBuffInfo(
    title: 'Giant\'s Draught',
    effects: <String>[
      'All AP +10',
      'Max HP +150',
      'All Special Attack Extra Damage +10%',
      'Movement Speed +3',
      'Critical Hit +3',
      'Max Stamina +200',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'glorious golden hand elixir': ExactBuffInfo(
    title: 'Glorious Golden Hand Elixir',
    effects: <String>['Luck +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'golden hand elixir': ExactBuffInfo(
    title: 'Golden Hand Elixir',
    effects: <String>['Luck +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'griffon\'s elixir': ExactBuffInfo(
    title: 'Griffon\'s Elixir',
    effects: <String>['Extra AP Against Kamasylvian Monsters +12'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'grim reaper\'s elixir': ExactBuffInfo(
    title: 'Grim Reaper\'s Elixir',
    effects: <String>['Recover 3 HP on Hits'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'grim soul reaper\'s elixir': ExactBuffInfo(
    title: 'Grim Soul Reaper\'s Elixir',
    effects: <String>['Recover 9 HP on Hits'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'harmony draught': ExactBuffInfo(
    title: 'Harmony Draught',
    effects: <String>[
      'All AP +13',
      'All Accuracy +13',
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
      'All Special Attack Extra Damage +18%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'harmony draught - demihuman': ExactBuffInfo(
    title: 'Harmony Draught - Demihuman',
    effects: <String>[
      'All AP +13',
      'Extra AP Against Demihumans +15',
      'All Accuracy +13',
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
      'All Special Attack Extra Damage +18%',
      'Monster Damage Reduction Rate +10%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'harmony draught - edania': ExactBuffInfo(
    title: 'Harmony Draught - Edania',
    effects: <String>[
      'All AP +13',
      'Extra AP Against Edanian Monsters +17',
      'All Accuracy +13',
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
      'All Special Attack Extra Damage +18%',
      'Monster Damage Reduction Rate +10%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'harmony draught - human': ExactBuffInfo(
    title: 'Harmony Draught - Human',
    effects: <String>[
      'All AP +13',
      'Extra AP Against Adventurers +11',
      'Extra AP Against Humans +11',
      'All Accuracy +13',
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
      'All Special Attack Extra Damage +18%',
      'Monster Damage Reduction Rate +10%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'harmony draught - kamasylvia': ExactBuffInfo(
    title: 'Harmony Draught - Kamasylvia',
    effects: <String>[
      'All AP +13',
      'Extra AP Against Kamasylvian Monsters +17',
      'All Accuracy +13',
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
      'All Special Attack Extra Damage +18%',
      'Monster Damage Reduction Rate +10%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'helix elixir': ExactBuffInfo(
    title: 'Helix Elixir',
    effects: <String>['All Evasion +8'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'immortal: adaptation draught': ExactBuffInfo(
    title: 'Immortal: Adaptation Draught',
    effects: <String>[
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: armor draught': ExactBuffInfo(
    title: 'Immortal: Armor Draught',
    effects: <String>[
      'All Damage Reduction +15',
      'All Evasion +10',
      'Monster Damage Reduction Rate +12%',
      'Max HP +300',
      'All Resistance +5%',
      'All AP -15',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: beast\'s draught': ExactBuffInfo(
    title: 'Immortal: Beast\'s Draught',
    effects: <String>[
      'Extra AP Against Monsters +15',
      'Combat EXP +20%',
      'Skill EXP +10%',
      'Recover 3 HP on Hits',
      'Monster Damage Reduction Rate +10%',
      'Critical Hit +3',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: berserk draught': ExactBuffInfo(
    title: 'Immortal: Berserk Draught',
    effects: <String>['All Special Attack Extra Damage +16%'],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: corruption draught': ExactBuffInfo(
    title: 'Immortal: Corruption Draught',
    effects: <String>[
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: elixir of indignation': ExactBuffInfo(
    title: 'Immortal: Elixir of Indignation',
    effects: <String>[
      'Extra AP Against Adventurers +25',
      'Extra AP Against Humans +25',
      'All Special Attack Extra Damage +12%',
      'Movement Speed +3',
      'Critical Hit +3',
      'Max Stamina +200',
      'Max HP -150',
      'All Damage Reduction -20',
      'All Evasion -20',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: frenzy draught': ExactBuffInfo(
    title: 'Immortal: Frenzy Draught',
    effects: <String>[
      'Extra AP Against Monsters +30',
      'All Accuracy +12',
      'Max Stamina +200',
      'Recover 9 HP on Hits',
      'All Damage Reduction -15',
      'Critical Hit Extra Damage +10%',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: frenzy draught of corruption': ExactBuffInfo(
    title: 'Immortal: Frenzy Draught of Corruption',
    effects: <String>[
      'Extra AP Against Monsters +35',
      'All Accuracy +12',
      'Max Stamina +200',
      'Recover 9 HP on Hits',
      'All Damage Reduction -15',
      'Critical Hit Extra Damage +10%',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: fury draught': ExactBuffInfo(
    title: 'Immortal: Fury Draught',
    effects: <String>[
      'All AP +13',
      'All Accuracy +13',
      'All Special Attack Extra Damage +2%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: giant\'s draught': ExactBuffInfo(
    title: 'Immortal: Giant\'s Draught',
    effects: <String>[
      'All AP +10',
      'Max HP +150',
      'All Special Attack Extra Damage +10%',
      'Movement Speed +3',
      'Critical Hit +3',
      'Max Stamina +200',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: harmony draught': ExactBuffInfo(
    title: 'Immortal: Harmony Draught',
    effects: <String>[
      'All AP +13',
      'All Accuracy +13',
      'All Damage Reduction +13',
      'All Evasion +13',
      'Max HP +200',
      'Max Stamina +200',
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
      'Deal 15 Fixed Damage on Back Attack Hits',
      'Deal 15 Fixed Damage on Critical Hits',
      'Recover 17 HP on Critical Hits',
      'Recover 12 HP on Hits',
      'All Special Attack Extra Damage +18%',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of bracing spirits': ExactBuffInfo(
    title: 'Immortal: Perfume of Bracing Spirits',
    effects: <String>[
      'Extra AP Against Monsters +5',
      'Max HP +300',
      'Critical Hit +5',
      'Recover 9 MP/WP/SP on Hits',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of charm': ExactBuffInfo(
    title: 'Immortal: Perfume of Charm',
    effects: <String>['All Evasion +25', 'Max HP +750', 'Movement Speed +5%'],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of courage': ExactBuffInfo(
    title: 'Immortal: Perfume of Courage',
    effects: <String>[
      'All AP +20',
      'Max HP +200',
      'Attack Speed +5',
      'Casting Speed +5',
      'Movement Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of deep sea': ExactBuffInfo(
    title: 'Immortal: Perfume of Deep Sea',
    effects: <String>[
      'All AP +10',
      'Max Stamina +100',
      'Max HP +100',
      'Back Attack Extra Damage +10%',
      'Down Attack Extra Damage +10%',
      'Air Attack Extra Damage +10%',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of envy': ExactBuffInfo(
    title: 'Immortal: Perfume of Envy',
    effects: <String>[
      'All AP +25',
      'Max HP +500',
      'Attack Speed +5',
      'Casting Speed +5',
      'Movement Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of insight': ExactBuffInfo(
    title: 'Immortal: Perfume of Insight',
    effects: <String>[
      'All Accuracy +15',
      'Max HP +100',
      'Attack Speed +5',
      'Casting Speed +5',
      'Movement Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of khalk': ExactBuffInfo(
    title: 'Immortal: Perfume of Khalk',
    effects: <String>[
      'All Resistance +10%',
      'All Damage Reduction +15',
      'Max HP +100',
      'Movement Speed +5%',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of spirits': ExactBuffInfo(
    title: 'Immortal: Perfume of Spirits',
    effects: <String>[
      'Max HP +300',
      'Critical Hit +5',
      'Recover 9 MP/WP/SP on Hits',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: perfume of tenacity': ExactBuffInfo(
    title: 'Immortal: Perfume of Tenacity',
    effects: <String>[
      'All AP +15',
      'Max Stamina +100',
      'Max HP +400',
      'Back Attack Extra Damage +10%',
      'Down Attack Extra Damage +10%',
      'Air Attack Extra Damage +10%',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'immortal: potential draught': ExactBuffInfo(
    title: 'Immortal: Potential Draught',
    effects: <String>[
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'immortal: savage draught': ExactBuffInfo(
    title: 'Immortal: Savage Draught',
    effects: <String>[
      'Extra AP Against Monsters +15 Knowledge Gain Chance +12% Higher Grade Knowledge Gain Chance +7%',
      'Recover 3 HP on Hits',
      'Monster Damage Reduction Rate +10%',
      'Critical Hit +3',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'improved elixir of amity': ExactBuffInfo(
    title: 'Improved Elixir of Amity',
    effects: <String>['Amity +30%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'looney elixir': ExactBuffInfo(
    title: 'Looney Elixir',
    effects: <String>['Higher Grade Knowledge Gain Chance +3%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'marvelous draught of persistence': ExactBuffInfo(
    title: 'Marvelous Draught of Persistence',
    effects: <String>[
      'Breath EXP +30%',
      'Movement Speed +5',
      'Max Stamina +200',
    ],
    duration: '600 min',
    cooldown: '10 sec',
  ),
  'marvelous draught of strength': ExactBuffInfo(
    title: 'Marvelous Draught of Strength',
    effects: <String>[
      'Strength EXP +30%',
      'Movement Speed +5',
      'Max Stamina +200',
    ],
    duration: '600 min',
    cooldown: '10 sec',
  ),
  'merciless sky elixir': ExactBuffInfo(
    title: 'Merciless Sky Elixir',
    effects: <String>['Air Attack Extra Damage +15%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'perfume of bracing spirits': ExactBuffInfo(
    title: 'Perfume of Bracing Spirits',
    effects: <String>[
      'Extra AP Against Monsters +5',
      'Max HP +300',
      'Critical Hit +5',
      'Recover 9 MP/WP/SP on Hits',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of charm': ExactBuffInfo(
    title: 'Perfume of Charm',
    effects: <String>['All Evasion +25', 'Max HP +750', 'Movement Speed +5%'],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of courage': ExactBuffInfo(
    title: 'Perfume of Courage',
    effects: <String>[
      'All AP +20',
      'Max HP +200',
      'Attack Speed +5',
      'Casting Speed +5',
      'Movement Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of deep sea': ExactBuffInfo(
    title: 'Perfume of Deep Sea',
    effects: <String>[
      'All AP +10',
      'Max Stamina +100',
      'Max HP +100',
      'Back Attack Extra Damage +10%',
      'Down Attack Extra Damage +10%',
      'Air Attack Extra Damage +10%',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of envy': ExactBuffInfo(
    title: 'Perfume of Envy',
    effects: <String>[
      'All AP +25',
      'Max HP +500',
      'Attack Speed +5',
      'Casting Speed +5',
      'Movement Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of insight': ExactBuffInfo(
    title: 'Perfume of Insight',
    effects: <String>[
      'All Accuracy +15',
      'Max HP +100',
      'Attack Speed +5',
      'Casting Speed +5',
      'Movement Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of khalk': ExactBuffInfo(
    title: 'Perfume of Khalk',
    effects: <String>[
      'All Resistance +10%',
      'All Damage Reduction +15',
      'Max HP +100',
      'Movement Speed 5%',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of spirits': ExactBuffInfo(
    title: 'Perfume of Spirits',
    effects: <String>[
      'Max HP +300',
      'Critical Hit +5',
      'Recover 9 MP/WP/SP on Hits',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of swiftness': ExactBuffInfo(
    title: 'Perfume of Swiftness',
    effects: <String>[
      'Weight Limit +200 LT',
      'Life EXP +20%',
      'Movement Speed +5',
      'Gathering Speed +5',
      'Fishing Speed +5',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of verdure': ExactBuffInfo(
    title: 'Perfume of Verdure',
    effects: <String>[
      'Life Mastery +50',
      'Life EXP +25%',
      'Movement Speed +5',
      'Gathering Speed +5',
      'Fishing Speed +5',
      'Weight Limit +300 LT',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'perfume of tenacity': ExactBuffInfo(
    title: 'Perfume of Tenacity',
    effects: <String>[
      'All AP +15',
      'Max Stamina +100',
      'Max HP +400',
      'Back Attack Extra Damage +10%',
      'Down Attack Extra Damage +10%',
      'Air Attack Extra Damage +10%',
    ],
    duration: '20 min',
    cooldown: '10 sec',
  ),
  'potential draught': ExactBuffInfo(
    title: 'Potential Draught',
    effects: <String>[
      'Movement and Attack/Casting Speeds +5',
      'Critical Hit +5',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'reliable looney elixir': ExactBuffInfo(
    title: 'Reliable Looney Elixir',
    effects: <String>['Higher Grade Knowledge Gain Chance +5%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'resurrection elixir': ExactBuffInfo(
    title: 'Resurrection Elixir',
    effects: <String>['HP Recovery +10'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'savage draught': ExactBuffInfo(
    title: 'Savage Draught',
    effects: <String>[
      'Extra AP Against Monsters +15 Knowledge Gain Chance +12% Higher Grade Knowledge Gain Chance +7%',
      'Recover 3 HP on Hits',
      'Monster Damage Reduction Rate +10%',
      'Critical Hit +3',
      'Weight Limit +100 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'skilled fisher\'s elixir': ExactBuffInfo(
    title: 'Skilled Fisher\'s Elixir',
    effects: <String>['Fishing Speed +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'skilled worker\'s elixir': ExactBuffInfo(
    title: 'Skilled Worker\'s Elixir',
    effects: <String>['Gathering Speed +3'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'soaring wings elixir': ExactBuffInfo(
    title: 'Soaring Wings Elixir',
    effects: <String>['Jump Height +30'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'splendid exp elixir': ExactBuffInfo(
    title: 'Splendid EXP Elixir',
    effects: <String>['Combat EXP +15%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'splendid helix elixir': ExactBuffInfo(
    title: 'Splendid Helix Elixir',
    effects: <String>['All Evasion +12'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'strong elixir of edania': ExactBuffInfo(
    title: 'Strong Elixir of Edania',
    effects: <String>['Extra AP Against Edanian Monsters +17'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'strong griffon\'s elixir': ExactBuffInfo(
    title: 'Strong Griffon\'s Elixir',
    effects: <String>['Extra AP Against Kamasylvian Monsters +17'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'strong resurrection elixir': ExactBuffInfo(
    title: 'Strong Resurrection Elixir',
    effects: <String>['HP Recovery +15'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'sturdy whale tendon elixir': ExactBuffInfo(
    title: 'Sturdy Whale Tendon Elixir',
    effects: <String>['All Damage Reduction +175'],
    duration: '30 sec',
    cooldown: '10 min',
  ),
  'surging energy elixir': ExactBuffInfo(
    title: 'Surging Energy Elixir',
    effects: <String>['MP Recovery +15'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'surging weenie elixir': ExactBuffInfo(
    title: 'Surging Weenie Elixir',
    effects: <String>['Knowledge Gain Chance +10%'],
    duration: '15 min',
    cooldown: '1 sec',
    party: true,
  ),
  'tidal draught': ExactBuffInfo(
    title: 'Tidal Draught',
    effects: <String>[
      'Fishing EXP +20%',
      'Fishing Speed +2',
      'Fishing Mastery +50',
    ],
    duration: '180 min',
    cooldown: '10 sec',
  ),
  'tough whale tendon elixir': ExactBuffInfo(
    title: 'Tough Whale Tendon Elixir',
    effects: <String>['All Damage Reduction +125'],
    duration: '30 sec',
    cooldown: '10 min',
  ),
  'unbridled celerity draught': ExactBuffInfo(
    title: 'Unbridled Celerity Draught',
    effects: <String>[
      'Mount EXP +15%',
      'Training EXP +20%',
      'Sailing EXP +20%',
      'Movement Speed +3',
    ],
    duration: '360 min',
    cooldown: '10 sec',
  ),
  'viridian draught': ExactBuffInfo(
    title: 'Viridian Draught',
    effects: <String>[
      'Life Mastery +25',
      'Life EXP +30%',
      'Alchemy/Cooking Time -3 sec',
      'Processing Success Rate +25%',
      'Movement Speed +3',
      'Gathering Speed +3',
      'Fishing Speed +3',
      'Weight Limit +300 LT',
    ],
    duration: '15 min',
    cooldown: '10 sec',
  ),
  'weenie elixir': ExactBuffInfo(
    title: 'Weenie Elixir',
    effects: <String>['Knowledge Gain Chance +7%'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
  'whale tendon elixir': ExactBuffInfo(
    title: 'Whale Tendon Elixir',
    effects: <String>['All Damage Reduction +100'],
    duration: '20 sec',
    cooldown: '10 min',
  ),
  'worker\'s elixir': ExactBuffInfo(
    title: 'Worker\'s Elixir',
    effects: <String>['Gathering Speed +2'],
    duration: '10 min',
    cooldown: '1 sec',
    party: true,
  ),
};
